test = {   'name': 'q2_3',
    'points': [0, 5],
    'suites': [   {   'cases': [   {'code': '>>> 0 < eth_predictor(10) < 100\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> np.allclose(eth_predictor(np.arange(10,15)), [ 2.6421542 ,  2.69252572,  2.74289723,  2.79326875,  2.84364026])\nTrue',
                                       'hidden': True,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
