test = {   'name': 'q3_6',
    'points': [0, 2, 2, 2],
    'suites': [   {   'cases': [   {'code': '>>> type(michelle_sample_size) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(estimated_population_sd, 0.4993746088859545)\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> michelle_sample_size == 9975\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> np.isclose(michelle_sample_mean_sd, .005)\nTrue', 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
